// <auto-generated />
using InstrumentsStore.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InstrumentsStore.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924230905_SeedInstrumentosFigma")]
    partial class SeedInstrumentosFigma
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("InstrumentsStore.Api.Models.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("GalleryUrls")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Installments")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("OldPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Instruments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Fender",
                            Category = "Cordas",
                            Description = "Clássica e versátil.",
                            GalleryUrls = "",
                            ImageUrl = "/images/guitarra.png",
                            Installments = 12,
                            Name = "Guitarra Elétrica Stratocaster",
                            Price = 1800.00m,
                            Section = "novo",
                            Slug = "guitarra",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Yamaha",
                            Category = "Sopro",
                            Description = "Acabamento laqueado.",
                            GalleryUrls = "",
                            ImageUrl = "/images/saxofone.png",
                            Installments = 12,
                            Name = "Saxofone Alto",
                            Price = 3500.00m,
                            Section = "exclusivo",
                            Slug = "saxofone",
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Roland",
                            Category = "Teclas",
                            Description = "61 teclas sensitivas.",
                            GalleryUrls = "",
                            ImageUrl = "/images/teclado.png",
                            Installments = 12,
                            Name = "Teclado Sintetizador",
                            OldPrice = 2500.00m,
                            Price = 2200.00m,
                            Section = "novo",
                            Slug = "teclado",
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Stradivarius",
                            Category = "Cordas",
                            Description = "Peça rara e restaurada.",
                            GalleryUrls = "",
                            ImageUrl = "/images/violino.png",
                            Installments = 12,
                            Name = "Violino Clássico",
                            Section = "exclusivo",
                            Slug = "violino",
                            StockQuantity = 1
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Pearl",
                            Category = "Percussão",
                            Description = "Kit completo com pratos.",
                            GalleryUrls = "",
                            ImageUrl = "/images/bateria.png",
                            Installments = 12,
                            Name = "Bateria Acústica",
                            OldPrice = 3500.00m,
                            Price = 2900.00m,
                            Section = "promocao",
                            Slug = "bateria",
                            StockQuantity = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
