// <auto-generated />
using System;
using InstrumentsStore.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InstrumentsStore.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("InstrumentsStore.Api.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "contato@chordstore.com",
                            PasswordHash = "100000.0iOmMqXGLxiV2B6nKB6njw==.rI4jbbCGMCeN3HanEUsapojoWm0zfKr2xRx8Hl2q3/o=",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("InstrumentsStore.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Violões, guitarras, baixos e violinos",
                            Name = "Cordas"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Saxofones, trompetes e afins",
                            Name = "Sopro"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Teclados, pianos e sintetizadores",
                            Name = "Teclas"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Baterias e instrumentos de percussão",
                            Name = "Percussão"
                        });
                });

            modelBuilder.Entity("InstrumentsStore.Api.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Document")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("InstrumentsStore.Api.Models.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("GalleryUrls")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Installments")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("OldPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("Instruments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Fender",
                            CategoryId = 1,
                            Description = "Clássica e versátil.",
                            GalleryUrls = "",
                            ImageUrl = "/images/guitarra.png",
                            Installments = 12,
                            Name = "Guitarra Elétrica Stratocaster",
                            Price = 1800.00m,
                            Section = "novo",
                            Slug = "guitarra",
                            StockQuantity = 15,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Yamaha",
                            CategoryId = 2,
                            Description = "Acabamento laqueado.",
                            GalleryUrls = "",
                            ImageUrl = "/images/saxofone.png",
                            Installments = 12,
                            Name = "Saxofone Alto",
                            Price = 3500.00m,
                            Section = "exclusivo",
                            Slug = "saxofone",
                            StockQuantity = 4,
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Roland",
                            CategoryId = 3,
                            Description = "61 teclas sensitivas.",
                            GalleryUrls = "",
                            ImageUrl = "/images/teclado.png",
                            Installments = 12,
                            Name = "Teclado Sintetizador",
                            OldPrice = 2500.00m,
                            Price = 2200.00m,
                            Section = "novo",
                            Slug = "teclado",
                            StockQuantity = 8,
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Stradivarius",
                            CategoryId = 1,
                            Description = "Peça rara e restaurada.",
                            GalleryUrls = "",
                            ImageUrl = "/images/violino.png",
                            Installments = 12,
                            Name = "Violino Clássico",
                            Section = "exclusivo",
                            Slug = "violino",
                            StockQuantity = 1,
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Pearl",
                            CategoryId = 4,
                            Description = "Kit completo com pratos.",
                            GalleryUrls = "",
                            ImageUrl = "/images/bateria.png",
                            Installments = 12,
                            Name = "Bateria Acústica",
                            OldPrice = 3500.00m,
                            Price = 2900.00m,
                            Section = "promocao",
                            Slug = "bateria",
                            StockQuantity = 3,
                            SupplierId = 5
                        });
                });

            modelBuilder.Entity("InstrumentsStore.Api.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerAddressSnapshot")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerEmailSnapshot")
                        .HasColumnType("longtext");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerNameSnapshot")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerPhoneSnapshot")
                        .HasColumnType("longtext");

                    b.Property<int>("Installments")
                        .HasColumnType("int");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("InstrumentsStore.Api.Models.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("InstrumentsStore.Api.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Document")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "vendas@fender.com.br",
                            Name = "Fender Brasil",
                            Phone = "(11) 4000-0001"
                        },
                        new
                        {
                            Id = 2,
                            Email = "vendas@yamaha.com.br",
                            Name = "Yamaha Brasil",
                            Phone = "(11) 4000-0002"
                        },
                        new
                        {
                            Id = 3,
                            Email = "vendas@roland.com.br",
                            Name = "Roland Brasil",
                            Phone = "(11) 4000-0003"
                        },
                        new
                        {
                            Id = 4,
                            Email = "contato@stradivarius-imports.com",
                            Name = "Stradivarius Imports",
                            Phone = "(11) 4000-0004"
                        },
                        new
                        {
                            Id = 5,
                            Email = "vendas@pearldrums.com.br",
                            Name = "Pearl Drums Brasil",
                            Phone = "(11) 4000-0005"
                        });
                });

            modelBuilder.Entity("InstrumentsStore.Api.Models.Instrument", b =>
                {
                    b.HasOne("InstrumentsStore.Api.Models.Category", "Category")
                        .WithMany("Instruments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InstrumentsStore.Api.Models.Supplier", "Supplier")
                        .WithMany("Instruments")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("InstrumentsStore.Api.Models.Sale", b =>
                {
                    b.HasOne("InstrumentsStore.Api.Models.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("InstrumentsStore.Api.Models.SaleItem", b =>
                {
                    b.HasOne("InstrumentsStore.Api.Models.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InstrumentsStore.Api.Models.Sale", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("InstrumentsStore.Api.Models.Category", b =>
                {
                    b.Navigation("Instruments");
                });

            modelBuilder.Entity("InstrumentsStore.Api.Models.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("InstrumentsStore.Api.Models.Sale", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("InstrumentsStore.Api.Models.Supplier", b =>
                {
                    b.Navigation("Instruments");
                });
#pragma warning restore 612, 618
        }
    }
}
